
# @package _global_
defaults:
  - /data@data_train.ds1: dclm_arrayrecord_train
  - /data@data_eval.ds1: dclm_arrayrecord_eval_preprocessed
  # - /data@data_eval.ds2: slimpajama_627B_arrayrecord_eval_preprocessed
  - override /parallel: mLSTMv1_1.3B #mLSTMv1_7B # use fsdp #mLSTMv1_1.3B # use this for no FSDP (pure dp)
  - override /model: mLSTMv1_default
  - override /optimizer: adamw
  - override /scheduler: cosine_decay
  - override /hydra/launcher: slurm_launcher
  - _self_

# specify the deltas from the defaults:
task_name: sclaw_mlstm_ctx_iso2 #! adapt here
batch_size_per_device: 64
context_length: 2048
num_epochs: 1000
num_train_steps: 27200 #18_000
lr: 0.003

scheduler:
  warmup_steps: 750
  cooldown_steps: 1000 #2000

trainer:
  gradient_accumulate_steps: 1
  check_val_every_n_steps: 1000
  log_logit_stats: true
  log_intermediates: true

checkpointing:
  monitor: dclm_perplexity

data_train:
  ds1:
    tokenizer_path: "EleutherAI/gpt-neox-20b"

data_eval:
  ds1:
    tokenizer_path: "EleutherAI/gpt-neox-20b"
  # ds2:
  #   tokenizer_path: "EleutherAI/gpt-neox-20b"

model:
  name: mLSTMv1_80M

  igate_bias_init_range: -10.0
  igate_preact_fixed_to: null
  cell_norm_type_v1: layernorm #layernorm #rmsnorm

  reset_at_document_boundaries: true
  vocab_size: -1
  backend: "triton_kernels"
  backend_name: "chunkwise--triton_limit_chunk"
  chunk_size: 64

  num_blocks: 10
  num_heads: 4
  embedding_dim: 512
  proj_factor: 2.667

profiling:
  # Not profiling to reduce time and potential failure points.
  profile_every_n_minutes: -1

base_dir: /nfs-gpu/xlstm/outputs_beck
logging_name: ${data_train.ds1.name}_${model.name}_ctx${context_length}_lr${lr}_steps${num_train_steps}_nb${model.num_blocks}_ed${model.embedding_dim}_nh${model.num_heads}_pf${model.proj_factor}

logger:
  wb_tags:
    - ${task_name}
    - ${model.name}
    - nb${model.num_blocks}_ed${model.embedding_dim}_nh${model.num_heads}_pf${model.proj_factor}
    - ${model.backend_name}
    - sclaw_mlstm_ctx_iso_round2 #! adapt here

# Run command:
# PYTHONPATH=. python scripts/training/train_with_hydra.py +experiment_sclaw=train_mLSTMv1_160M_dclm_cosine
hydra:
  launcher:
    nodes: 1
    additional_parameters: {
      "gpu-bind": "closest",
      "wait-all-nodes": "1",
      "time": "21-00:00:00",
      "exclusive": "",
    }
  mode: MULTIRUN
  sweeper:
    params:
      num_train_steps: 27200
