defaults:
  - model_schema
  - _self_

name: mLSTM7B
# xLSTMLMModelConfig
vocab_size: 50304
embedding_dim: 4096
num_blocks: 64
context_length: ${context_length}
tie_weights: false
add_embedding_dropout: false
add_post_blocks_norm: true
dtype: bfloat16
scan_blocks: true
# mLSTMLayerConfig
num_heads: 8
# mLSTMCellConfig
gate_dtype: float32
