defaults:
  - logger_schema
  - _self_

# General LoggerConf parameters
log_path: ${hydra:runtime.output_dir}
cmd_logging_name: ${hydra:job.name}
log_every_n_steps: 50

loggers_to_use:
  - file_logger
  - tb_logger
  - wb_logger

# For now, the parameters for the sub-configs are also defined here
# FileLoggerConfig
file_logger_log_dir: file_logs
file_logger_config_format: json

# TensorBoardLoggerConfig
tb_log_dir: tensorboard
tb_flush_secs: 120

# WandBLoggerConfig
wb_project: xlstm_jax
wb_entity: xlstm
wb_name: ${logging_name}_gbs${global_batch_size}
wb_tags:
  - ${task_name}
  - ${logging_name}
