# @package _global_
defaults:
  - /data@data_train.ds1: dclm_arrayrecord_train
  - /data@data_eval.ds1: slimpajama_627B_arrayrecord_eval_preprocessed
  - /data@data_eval.ds2: dclm_arrayrecord_eval_preprocessed
  - override /parallel: llama7B # fsdp
  - override /model: llama_default
  - override /optimizer: adamw
  - override /scheduler: cosine_decay
  - override /hydra/launcher: slurm_launcher
  - _self_

# specify the deltas from the defaults:
task_name: sclaw
batch_size_per_device: 8
context_length: 8192
num_epochs: 1000
num_train_steps: 76_000
lr: 5e-4

scheduler:
  warmup_steps: 750
  cooldown_steps: 1000 #2000

trainer:
  gradient_accumulate_steps: 1
  check_val_every_n_steps: 500
  log_logit_stats: false
  log_intermediates: false

checkpointing:
  monitor: dclm_perplexity

data_train:
  ds1:
    tokenizer_path: "EleutherAI/gpt-neox-20b"
    batch_rampup_factors:
      0: 0.25
      1_000: 0.5
      2_000: 1.0


data_eval:
  ds1:
    tokenizer_path: "EleutherAI/gpt-neox-20b"
  ds2:
    tokenizer_path: "EleutherAI/gpt-neox-20b"

model:
  name: llama_7B

  reset_at_document_boundaries: true
  vocab_size: -1

  theta: 500_000

  num_blocks: 24
  head_dim: 128 #@32 heads
  embedding_dim: 4096

profiling:
  # Not profiling to reduce time and potential failure points.
  profile_every_n_minutes: -1

base_dir: /nfs-gpu/xlstm/outputs_beck
logging_name: ${data_train.ds1.name}_${model.name}_ctx${context_length}_lr${lr}_steps${num_train_steps}

# Run command:
# PYTHONPATH=. python scripts/training/train_with_hydra.py +experiment_sclaw=train_mLSTMv1_1.4B_dclm_cosine
hydra:
  launcher:
    nodes: 8
    additional_parameters: {
      "gpu-bind": "closest",
      "wait-all-nodes": "1",
      "time": "21-00:00:00",
      "exclusive": "",
      "exclude": "",
    }
  mode: MULTIRUN
  # this will start the runs locally and serially, i.e. submitit will wait until the first jobs is done
  # sweeper:
  #   params:
  #     lr: 7e-4, 1e-3
