name: jax0432_cpu
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.11
  - pip:
      - dacite==1.8.1
      - flax==0.9.0
      - jax==0.4.32
      - jaxlib==0.4.32
      - opt-einsum==3.3.0
      - optax==0.2.3
      - optree==0.12.1
      - orbax==0.1.9
      - orbax-checkpoint==0.6.1
      - pandas
      - pytest==8.3.2
      - tabulate==0.9.0
      - tensorflow==2.17.0
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - tqdm
      - grain
      - datasets
      - transformers
      - wandb
      - hydra-core
      - hydra-submitit-launcher
