# @package _global_
defaults:
  - config_schema
  - parallel: synthetic
  - data: synthetic
  - model: mLSTM120M
  - scheduler: exponential_decay
  - optimizer: adamw
  - checkpointing: model_checkpointing
  - lr_monitor: lr_monitor_config
  - profiling: jax_profiling
  - logger: default_logger
  - trainer: default_trainer
  - _self_


# General hyperparameters. Will be put in their respective config modules once they are created.

# Device. cpu or gpu
device: gpu
device_count: 1   # note: this is only used when using device=cpu and specifies the number of devices
                  #       that jax simulates on a CPU. Useful for multi-process debugging.

# Training-related
batch_size_per_device: 8  # will be multiplied by the number of devices used to obtain the global batch size
global_batch_size: ???
lr: 1e-3
context_length: 2048
num_epochs: 1000
#num_train_steps: 95_000

# Task name determines output directory
task_name: ??? # must be set in the experiment file
logging_name: ${data.name}_${model.name}_ctx${context_length}

# Set hydra working dir
base_dir: /nfs-gpu/xlstm/logs/outputs/xlstm-jax # this should be changed when running local experiments
hydra:
  run:
    dir: ${base_dir}/${task_name}/${logging_name}_${now:%Y-%m-%dT%H:%M:%S}
  sweep:
    dir: ''
    subdir: ${hydra.run.dir}_${hydra.job.num}
