name: License Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check license headers
      uses: viperproject/check-license-header@v2
      with:
        path: ./
        config: ./.github/license-check/config.json
        strict: false
